# Generated by Django 3.1.7 on 2021-03-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaverShopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='네이버 상품명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='가격')),
            ],
            options={
                'db_table': 'naver_shopping',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='상품명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='가격')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
