# Generated by Django 3.1.7 on 2021-03-31 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_navershopping_product'), ('core', '0003_auto_20210325_1236'), ('core', '0004_auto_20210325_1304'), ('core', '0005_auto_20210326_0439'), ('core', '0006_auto_20210331_1458'), ('core', '0007_auto_20210331_1502'), ('core', '0008_auto_20210331_1505'), ('core', '0009_auto_20210331_1506')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='상품명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='NaverCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='네이버 카테고리 코드')),
                ('name', models.CharField(max_length=50, verbose_name='네이버 카테고리 이름')),
            ],
            options={
                'db_table': 'naver_categories',
            },
        ),
        migrations.CreateModel(
            name='NaverShopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='네이버 상품명')),
                ('price_pc', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='가격')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('is_satisfied', models.BooleanField(default=False)),
                ('naver_id', models.CharField(default=1, max_length=50, verbose_name='네이버 ID')),
            ],
            options={
                'db_table': 'naver_shopping',
                'verbose_name_plural': '네이버 쇼핑 연동',
            },
        ),
        migrations.CreateModel(
            name='NaverShoppingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naver_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.navercategory')),
                ('naver_shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.navershopping')),
            ],
            options={
                'verbose_name_plural': '네이버 서브 카테고리 중간 테이블',
                'db_table': 'naver_shopping__categories',
            },
        ),
    ]
