# Generated by Django 3.1.7 on 2021-03-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_squashed_0009_auto_20210331_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navershopping',
            name='naver_id',
            field=models.CharField(max_length=50, verbose_name='네이버 ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
