# Generated by Django 3.1.7 on 2021-03-26 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210325_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navershopping',
            options={'verbose_name_plural': '네이버 쇼핑 연동'},
        ),
        migrations.AlterField(
            model_name='navershopping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
